require:
  - rubocop-performance
  - rubocop-minitest

AllCops:
  NewCops: enable

Layout/LineLength:
  Enabled: false

Metrics:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Gemspec/RequireMFA:
  Enabled: false

Style/SymbolProc:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/ConditionalAssignment:
  Enabled: false

Style/EmptyMethod:
  EnforcedStyle: expanded

Style/ParenthesesAroundCondition:
  Enabled: false

Layout/HashAlignment:
  Enabled: false

Layout/ParameterAlignment:
  Enabled: false

# disabled until we can configure "+" as concat sign
Style/LineEndConcatenation:
  Enabled: false

Style/ParallelAssignment:
  Enabled: false

Style/PreferredHashMethods:
  Enabled: false

Style/MultipleComparison:
  Enabled: false

Style/SymbolArray:
  Enabled: false
